### ISSUE TITLE
Determine status of downloaded books

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/google-books#88] opened 2020-01-08 19:17 UTC
It appears that once a book has been converted and downloaded, at some point the download disappears and requesting a new conversion does not actually result in a new conversion. 

We may have to go to Google and ask them to reset everything so that we can start fresh.

- [ ]  verify the status of previously downloaded books
- [ ]  try to request a previously downloaded book

**Comment by aaron-collier** [comment] 2020-01-08 19:43
Follow up:

- I can still download, repeatedly, from the web interface
- I cannot download a previously downloaded file through the API

**Comment by mjgiarlo** [comment] 2020-01-27 21:41
Duplicate of #163. Closing.

**Closed by mjgiarlo** 2020-01-27 21:41 UTC
Labels: question
